config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  get "/privacy" => "pages#privacy"

  resources :admins, only: [:index]
  resources :subscribers, only: [:new, :create, :index, :show]


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :first_name, :presence => true, :length => { minimum: 2 }
  validates_format_of :first_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/

  validates :last_name, :presence => true, :length => { minimum: 2 }
  validates_format_of :first_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/

  validates :email, :presence => true, :uniqueness => true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates_acceptance_of :privacy_policy, :message => ' The privacy policy must be accepted'


  

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :check_for_login, :only => [:index]
  def index
    @admins = Admin.all
  end

  # def new
  #   @admin = Admin.new
  # end

  # def create
  #   @admin = Admin.new admin_params
  #   if @admin.save # returns true on success
  #     session[:admin_id] = @admin.id
  #     redirect_to root_path
  #   else
  #     render :new
  #   end
  # end


  private
  def admin_params
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_admin

  private
  def fetch_admin
    @current_admin = Admin.find_by :id => session[:admin_id] if session[:admin_id].present?
    session[:admin_id] = nil unless @current_admin.present? # Log out non-existen admins.
  end

  def check_for_login
    redirect_to login_path unless @current_admin.present?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def privacy
    render :template => "pages/privacy.html.erb"
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create

    admin = Admin.find_by :email => params[:email]
    if admin.present? && admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      redirect_to subscribers_path
    else
      redirect_to login_path # GET /login
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to login_path # GET login
  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :check_for_login, :only => [:index]
  helper_method :sort_column, :sort_direction


  def new
    @subscriber = Subscriber.new
  end

  def show
    # @subscriber = Subscriber.find params[:id]
    # raise 'hell'
  end

  def create
    @subscriber = Subscriber.new subscriber_params
    if @subscriber.save
      redirect_to subscriber_path @subscriber
    else
      render :new
    end
  end

  def index

    @subscribers = Subscriber
      .page(params[:page]).per(10)
      # .order(sort_by + " " + direction)
      .order(sort_column + " " + sort_direction)
    @last_day_subs = Subscriber.all.where("DATE(created_at) = ?", Date.today - 1).count
    @total_subs = Subscriber.all.count
  end

  private
  # def define_order(attribute)
  #   attribute.start_with?("-") ? :desc : :asc
  #   sort_direction == "asc" ? "desc" : "asc"
  # end
  # Direction "created_at" is invalid. Valid directions are: [:asc, :desc, :ASC, :DESC, "asc", "desc", "ASC", "DESC"]
  # def sort_by
  #   %w{first_name email created_at}.include?(params[:sort_by]) ? params[:sort_by] : 'first_name'
  # end
  #
  # def direction
  #   %w{asc desc}.include?(params[:direction] == "asc") ? "desc" : "asc"
  # end
  def sort_column
    Subscriber.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
  end
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
  def subscriber_params
    params.require(:subscriber).permit(:first_name, :last_name, :email, :innovation, :botler_care, :updates, :special_deals)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}
  end
end

app/views/admins/index.html.erb
<h1>List of Admins</h1>

<%  @admins.each do |admin| %>
  <p><%= admin.email  %></p>
<% end %>

app/views/admins/new.html.erb
<h1>Admin#new</h1>
<p>Find me in app/views/admin/new.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="container top-nav mx-auto m-0">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to('BOTLERS.COM',root_path, :class =>'navbar-brand') %>
    <button
      class="navbar-toggler"
      data-toggle="collapse"
      data-target="#navbarMenu"
    >
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarMenu">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item"><a class="nav-link" href="#">ABOUT</a></li>
        <li class="nav-item"><a class="nav-link" href="#">PRODUCTS</a></li>
        <li class="nav-item"><a class="nav-link" href="#">SUPPORT</a></li>
        <li class="nav-item"><a class="nav-link" href="#">CONTACT</a></li>
        <li class="nav-item"><a class="nav-link" href="#">NEWSLETTER</a></li>
        <li class="nav-item"><a class="nav-link" href="#">MY&nbsp;ACCOUNT</a></li>
      </ul>
    </div>
    <ul class="navbar-nav">
      <% if @current_admin.present? %>
        <%= link_to "LOGOUT", login_path, :method => 'delete', :class => 'nav-link session' %>
      <% else %>
        <%# link_to "LOGIN", login_path, :class => 'nav-link session' %>
        <li class="nav-item"><a class="nav-link session" href="/login">LOGIN</a></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Botlers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render partial: "layouts/navbar" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-page">
  <div class="container text-center mb-4">
    <img class="news-logo" src="botlerlogo.png" alt="botler logo">
    <h1>Welcome to Botlers!</h1>
    <br>
    <p class="intro">
      Never lift a finger again  <br> with our adorable range of household assistants.
    </p>
    <br>
    <p>
      BROWSE  PRODUCTS
    </p>
    <img src="triangle.png" alt="arrow pointing down">
  </div>

  <div class="container kitchen text-center d-sm-inline-flex px-sm-5">
    <div class="container">
      <img class="home-toaster" src="toaster.png" alt="toaster image">
    </div>

    <div class="container text-left">
      <div class="">
        <br>
        <h2>Kitchen Bots</h2>
        <p>Cooking has never been easier with our talented and intuitive kitchen bots. Cocktails anyone?</p>
      </div>
      <div class="">
        <button id="browse-red" class="btn btn-primary px-5">
          BROWSE
        </button>
      </div>

    </div>
  </div>

  <div class="container cleaning text-center d-sm-inline-flex px-sm-5">
    <div class="extra-padding text-sm-right d-sm-inline-flex px-sm-5">
      <div class="container order-1 ">
        <img class="home-vaccume" src="vaccume.png" alt="vaccum cleaner image">
      </div>
      <div class="container order-0 text-left">
        <div class="">
          <br>
          <h2>Cleaning Bots</h2>
          <p>Never take out the garbage again with our super tidy range of washing, scrubbing and mopping bots.</p>
        </div>
        <div class="">
          <button id="browse-green" class="btn btn-primary px-5">
            BROWSE
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="container laundry text-center d-sm-inline-flex px-sm-5">
    <div class="container">
      <img class="home-laundry" src="washer.png" alt="washing machine image">
    </div>
    <div class="container text-left">
      <div class="">
        <br>
        <h2>Laundry Bots</h2>
        <p>Have your cardigans washed and your linen pressed while you spend the rest of your days in leisure.</p>
      </div>
      <div class="">
        <button id="browse-yellow" class="btn btn-primary px-5">
          BROWSE
        </button>
      </div>
    </div>
  </div>

  <div class="container quiz text-center">
    <img class="home-quiz" src="microwave.png" alt="microwave image">
    <div class="container text-center">
      <br>
      <h2>Spoiled for choice?</h2>
      <p>Take this quiz to see which bot could be your best bud.</p>
      <button class="btn btn-primary px-5">
        TAKE THE QUIZ
      </button>
    </div>
  </div>

  <div class="container signup-newsletter text-center d-sm-inline-flex">
    <div class="container text-left d-sm-inline-flex px-sm-5">
      <div class="container text-left">
        <h2 class="white-h2">Sign up to our  newsletter!</h2>
        <p>Stay informed on the latest bot-tech, system updates and get <strong>10% off your next purchase</strong> by signing up to the Monthly Botler Newsletter.</p>
      </div>
      <div class="container text-sm-center">
        <br>
        <button id="browse-white" class="btn btn-primary px-5">
          <%= link_to("SIGN ME UP!", new_subscriber_path) %>
        </button>
      </div>
    </div>
  </div>

  <div class="container footer-nav p-0">

    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link about" aria-current="page" href="#">ABOUT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link our-products" href="#">OUR PRODUCTS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">SUPPORT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">CONTACT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">MY ACCOUNT</a>
      </li>
      <li class="nav-item">
        <img class="fb-logo" src="facebook.png" alt="facebook logo">
        <img class="twitter-logo" src="twitter.png" alt="twitter logo">
      </li>
    </ul>

  </div>
</div>

app/views/pages/privacy.html.erb
<h1>HeyBotler.com Privacy Policy</h1>

<h3>Introduction</h3>
<p>HeyBotler.com Privacy Policy</p>
<p>Welcome and thank you for visiting the HeyBotler.com (Botler) website (this site and any other Botler sites are referred to as the “Site”). Please read through this Privacy Policy carefully as it contains important information about how Botler collects and uses your personal information.</p>
<p>Botler offers an easy to use chatbot platform that lets users create bots and interact with bots (with or without accounts)</p>
<p>Here are a few terms we use throughout this Privacy Policy that you should know:</p>
<p>“Users” are individuals who have signed up to create an account on the Site, or individuals who interact with bots on the platform without creating an account.</p>
<p>“Personal Information” is: (i) information that directly identifies you as an individual, like your name or your email address, or (ii) a combination of pieces of information that do not identify you on their own, but could identify you when combined using reasonable effort.</p>
<p>This Privacy Policy describes how Botler. (“Botler”, “we”, “us” and/or “our”) collects, uses, shares and secures the Personal Information (defined below) of Users in connection with our provision of the Site, and any other products or services we may offer from time to time (collectively, the “Services”).</p>
<p>We may also obtain information, including Personal Information, from publicly available sources or third parties, and combine this information with the Personal Information you provide to us.</p>
<p>By using the Services and/or providing us with your Personal Information, you agree to the processing of your Personal Information in the manner set out in this Privacy Policy.</p>
<p>Botler is not made for use in the European Union (EU) and users from the EU are discouraged from making accounts. If you are from the EU and would like your information removed from our Site, as defined in the Policy below, please email us at contact@heybotler.com.</p>

<h3>Scope</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur et vero debitis inventore cupiditate nihil asperiores, natus cum reiciendis laudantium aut tempore consequuntur velit doloribus impedit totam officiis at soluta.</p>

<h3>Personal Information Collected Through The Services</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam ea fugiat doloribus voluptate, eos totam nostrum, commodi adipisci modi alias. Voluptas velit nostrum ab odit, facere tempora quasi consequuntur dolore.</p>

<h3>Cookies</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam possimus natus nihil dolores cum, magnam, optio animi laudantium ea perspiciatis, officia tempore. Numquam modi voluptate, dicta quos eaque. Voluptates, quasi.</p>

app/views/session/new.html.erb
<div class="login-page">
  <div class="container text-center mb-4">
    <img class="news-logo" src="botlerlogo.png" alt="botler logo">
    <h1>Log In</h1>
  </div>

  <div class="container login-bg">
    <%= form_tag login_path do %>
      <div class="form-group">
        <%= label_tag :email %>
        <%= email_field_tag :email, nil, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password, nil, :class => 'form-control' %>
      </div>

      <div class="container text-center">
        <%= submit_tag "LOG IN", :class => 'btn btn-primary px-5' %>
      </div>
    <% end %>
  </div>
</div>

app/views/subscribers/index.html.erb
<div class="container text-center mb-4">
  <img class="news-logo" src="botlerlogo.png" alt="botler logo">
  <h1>Newsletter Analytics</h1>
</div>

<div class="container subscriber-bg">
  <div class="container d-flex flex-column flex-md-row text-center justify-content-evenly p-0 pt-4 pb-5">
    <div class="container-sm border-test border text-center m-3 p-0">
      <h4>New Subscribers Yesterday</h4>
      <h3><%= @last_day_subs %></h3>
    </div>
    <div class="container-sm text-center border rounded m-3 p-0">
      <h4>Total Subscribers</h4>
      <h3><%= @total_subs %></h3>
    </div>
    <div class="container-sm text-center border rounded m-3 p-0">
      <h4>Total Unsubscribes</h4>
      <h3>1</h3>
    </div>
  </div>
  <div class="container text-center">
    <div>
      <div class="container d-flex flex-column flex-md-row text-center justify-content-between p-0 pb-2">
        <div class="newsletter">
          <h2>Newsletter Sign-up Data</h2>
        </div>
        <div class="search-box">
          <%= form_tag(subscribers_path, method: :get) do %>
          <%= text_field_tag(:search, params[:search], placeholder: "Search for keywords") %>
          <%= submit_tag ("Search") %>
          <% end %>
        </div>
      </div>

      <table class="table-responsive table-borderless">
        <thead class="newsletter-header">
          <tr>
            <th scope="col" class="subscribers-link"><%= sortable "first_name", "Name" %></th>
            <th scope="col" class="subscribers-link"><%= sortable "email", "Email" %></th>
            <th scope="col" class="subscribers-link"><%= sortable "created_at", "Sign-up Date"%></th>
            <th scope="col">Interests</th>
          </tr>
        </thead>

        <tbody>
          <%  @subscribers.each do |subscriber| %>
            <tr class="newsletter-rows">
              <td scope="row"><%= subscriber.first_name %> <%= subscriber.last_name %></td>
              <td scope="row"><%= subscriber.email  %></td>
              <td scope="row"><%= subscriber.created_at.strftime '%e/%m/%Y' %></td>
              <td scope="row">
                <% if subscriber.innovation? %>
                  <%= "Innovation"%>
                  <% if subscriber.botler_care? || subscriber.updates? || subscriber.special_deals? %>
                    <%="|" %>
                  <% end %>
                <% end %>
                <% if subscriber.botler_care? %>
                  <%= "Botler Care"  %>
                  <% if subscriber.updates? || subscriber.special_deals? %> <%= "|" %><% end %>
                <% end %>
                <% if subscriber.updates? %>
                  <%= "Updates"  %>
                  <% if subscriber.special_deals? %> <%= "|" %><% end %>
                <% end %>
                <% if subscriber.special_deals? %>
                  <%= "Special Deals"  %>
                <% end %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
      <div class="container d-flex flex-column flex-md-row text-center justify-content-between p-0 pb-5 pt-2">
        <div class="news-subscribers"><%= page_entries_info @subscribers %></div>
        <div class="news-pages"><%= paginate @subscribers %></div>
      </div>

    </div>
  </div>
</div>

app/views/subscribers/new.html.erb
<div class="row justify-content-center">
  <div class="col center-block">
    <%= image_tag("botlerlogo.png", width: "180px" , alt: "botlers logo", :class => 'center-block') %>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-8 text-center">
    <h3>Join the Botler newsletter.</h3>
    <p>Every month we send an editorial newsletter with the latest bot-tech, tips, on caring for your Botlers, upcoming products and special deals.<strong>Subscribe now and get 10% off your next purchase!</strong></p><br>
  </div>
</div>

<div class="row  colbtm-bg justify-content-center">
  <div class="col-5">
    <% if @subscriber.errors.any? %>
      <ol>
        <% @subscriber.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ol>
    <% end %>
    <%= form_for @subscriber do |f|  %>
      <div class="form-group">
        <%= f.label       :first_name,"First Name*" %>
        <%= f.text_field :first_name, :required => true, :class => 'form-control'  %>
      </div>
      <div class="form-group">
        <%= f.label       :last_name,"Last Name*" %>
        <%= f.text_field :last_name, :required => true, :class => 'form-control'  %>
      </div>
      <div class="form-group">
        <%= f.label       :email,"Email* " %>
        <%= f.email_field :email, :required => true, :class => 'form-control'  %>
      </div>

      <div class="form-check">
        <%= f.check_box :innovation, :class => "form-check-input" %>
        <%= f.label :innovation, "Innovation" %><br>

        <%= f.check_box :botler_care, :class => "form-check-input" %>
        <%= f.label :botler_care, "Botler care" %><br>

        <%= f.check_box :updates, :class => "form-check-input" %>
        <%= f.label :updates, "Updates" %><br>

        <%= f.check_box :special_deals, :class => "form-check-input" %>
        <%= f.label :special_deals, "Special deals" %><br>

        <%= check_box :user, :terms_of_service, class: "form-check-input", required: true %>
        <%= label :terms_of_service, class: "form-check-label" do %>
          <span>I agree with the <%= link_to 'Privacy policy ', privacy_path %>*</span>
        <% end %>
      </div>

      <p>Botler takes your privacy very seriously, we will not share your information and you can opt out anytime.</p>
      <%= f.submit "SIGN ME UP!", class: "btn btn-default" %>
    <% end %>
  </div>
</div>
<div class="container footer-nav p-0">

  <ul class="nav flex-column">
    <li class="nav-item">
      <a class="nav-link about" aria-current="page" href="#">ABOUT</a>
    </li>
    <li class="nav-item">
      <a class="nav-link our-products" href="#">OUR PRODUCTS</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">SUPPORT</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">CONTACT</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">MY ACCOUNT</a>
    </li>
    <li class="nav-item">
      <img class="fb-logo" src="facebook.png" alt="facebook logo">
      <img class="twitter-logo" src="twitter.png" alt="twitter logo">
    </li>
  </ul>

</div>

app/views/subscribers/show.html.erb
<div class="row justify-content-center">
  <div class="col center-block">
    <%= image_tag("botlerlogo.png", width: "180px" , alt: "botlers logo", :class => 'center-block') %>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-8 text-center">
    <h3>Thanks for subscribing!</h3>
    <p>You just made my day!</p>
    <p>Find your 10% code in your welcome email</p><br>
    <%= link_to 'TAKE ME HOME', root_path, :class => "take-home" %>
  </div>
</div>

<div class="row  colbtm-bg-1 justify-content-center">
  <div class="col center-block">
    <%= image_tag("quiz-bot.png", width: "180px" , alt: "botlers logo", :class => 'center-block') %>
  </div>
</div>
<div class="row colbtm-bg-1 justify-content-center">
  <div class="col-6 text-center">
    <h3>Spoiled for choice!</h3>
    <p>Take this quiz to see which bot could be your best bud.</p>
    <%# link_to 'TAKE ME HOME', root_path, :class => "take-home" %>
    <button>TAKE THE QUIZ</button>
  </div>
</div>
<div class="container footer-nav p-0">

  <ul class="nav flex-column">
    <li class="nav-item">
      <a class="nav-link about" aria-current="page" href="#">ABOUT</a>
    </li>
    <li class="nav-item">
      <a class="nav-link our-products" href="#">OUR PRODUCTS</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">SUPPORT</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">CONTACT</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">MY ACCOUNT</a>
    </li>
    <li class="nav-item">
      <img class="fb-logo" src="facebook.png" alt="facebook logo">
      <img class="twitter-logo" src="twitter.png" alt="twitter logo">
    </li>
  </ul>

</div>